# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/development.sqlite3


production:
  adapter: postgresql
  encoding: unicode
  database: sample_development
  username: postgres
  password:
  host: localhost
  port: 5432